cmake_minimum_required(VERSION 3.30)

project( vroum )

add_library( vroum SHARED )

# C++ Standard
target_compile_features(vroum PUBLIC
	cxx_std_17
)

# Source files
target_sources( vroum PRIVATE
  source/window/sdl_wrapper.cpp
  source/window/sdl_wrapper.hpp
  source/window/input.cpp
  source/window/input.hpp
  source/window/events.hpp
  source/window/window_system.cpp
  source/window/window_system.hpp

  source/graphics/gl/vertex_array.cpp
  source/graphics/gl/vertex_array.hpp

  source/graphics/gpu_device.cpp
  source/graphics/gpu_device.hpp
  source/graphics/rendering_system.cpp
  source/graphics/rendering_system.hpp
  source/graphics/render_cmd.hpp
  
  source/core/logger.cpp
  source/core/logger.hpp
  source/core/errors.hpp
  source/core/errors.cpp
  source/core/engine_parameters.hpp
  source/core/engine_parameters.hpp
  source/core/slot_map.hpp

  source/layer.hpp
  source/engine.cpp
  source/engine.hpp
)

# Do not build any example / tests
set(JSON_BuildTests OFF CACHE INTERNAL "")
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/$<CONFIGURATION>")
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/$<CONFIGURATION>")

# Libraries
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/dependencies/json EXCLUDE_FROM_ALL)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/dependencies/simplex_noise)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/dependencies/glm EXCLUDE_FROM_ALL)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/dependencies/SDL3 EXCLUDE_FROM_ALL)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/dependencies/SDL3_image EXCLUDE_FROM_ALL)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/dependencies/sockpp EXCLUDE_FROM_ALL)
add_subdirectory(${CMAKE_CURRENT_SOURCE_DIR}/dependencies/glad EXCLUDE_FROM_ALL)

# Link libraries
target_link_libraries(vroum PUBLIC
  simplex_noise
  glm
  nlohmann_json::nlohmann_json
  SDL3::SDL3
  SDL3_image::SDL3_image
  sockpp
  glad
)

# Header files
target_include_directories(vroum PUBLIC
  ${CMAKE_CURRENT_SOURCE_DIR}/source
)